### ISSUE TITLE
Add mechanism to auto-bump golang-shared package

### ISSUE THREAD

**Issue by sophiewigmore** [cloudfoundry/cflinuxfs4-release#6]
We should implement a mechanism to autobump the golang-shared package in this BOSH release so we can stay up-to-date and avoid golang CVEs in our stack.

There are CI tasks to do this here: https://github.com/cloudfoundry/bosh-package-golang-release/tree/main/ci/tasks/shared

**Comment by sophiewigmore** [comment]
will likely tackle this as a part of https://github.com/pivotal-cf/tanzu-cflinuxfs3-release/issues/3

**Comment by arjun024** [comment]
Assigning to self (since I don't have perm to use UI)
